import { Trade, PerformanceMetric, DailyPerformance, PairPerformance, TradeDistribution, TradingSession } from './types';

export const dummyTrades: Trade[] = [
  {
    id: '1',
    pair: 'EUR/USD',
    type: 'BUY',
    entryDate: '2024-04-20T10:30:00',
    entryPrice: 1.0921,
    exitDate: '2024-04-20T16:45:00',
    exitPrice: 1.0965,
    stopLoss: 1.0890,
    takeProfit: 1.0970,
    lotSize: 0.5,
    commission: 2.5,
    swap: 0,
    profit: 220,
    pips: 44,
    riskRewardRatio: 2.1,
    notes: 'Strong trend continuation with price breaking above resistance',
    tags: ['Good Setup', 'Technical'],
    strategy: 'Trend Following',
    status: 'CLOSED',
    session: 'LONDON',
    capitalGrowth: 220,
    riskPercentage: 1.5
  },
  {
    id: '2',
    pair: 'GBP/USD',
    type: 'SELL',
    entryDate: '2024-04-21T09:15:00',
    entryPrice: 1.2510,
    exitDate: '2024-04-21T11:20:00',
    exitPrice: 1.2475,
    stopLoss: 1.2540,
    takeProfit: 1.2450,
    lotSize: 0.3,
    commission: 1.8,
    swap: 0,
    profit: 105,
    pips: 35,
    riskRewardRatio: 1.7,
    notes: 'Bearish engulfing pattern at resistance level',
    tags: ['Technical', 'Good Setup'],
    strategy: 'Price Action',
    status: 'CLOSED',
    session: 'LONDON',
    capitalGrowth: 105,
    riskPercentage: 1.5
  },
  {
    id: '3',
    pair: 'USD/JPY',
    type: 'BUY',
    entryDate: '2024-04-21T14:00:00',
    entryPrice: 153.25,
    exitDate: '2024-04-21T19:30:00',
    exitPrice: 152.85,
    stopLoss: 152.80,
    takeProfit: 154.00,
    lotSize: 0.2,
    commission: 1.5,
    swap: 0,
    profit: -80,
    pips: -40,
    riskRewardRatio: 2.5,
    notes: 'Failed breakout, market reversed quickly after entry',
    tags: ['Bad Entry', 'Choppy Market'],
    strategy: 'Breakout',
    status: 'CLOSED',
    session: 'TOKYO',
    capitalGrowth: -80,
    riskPercentage: 1.5
  },
  {
    id: '4',
    pair: 'EUR/USD',
    type: 'SELL',
    entryDate: '2024-04-22T08:45:00',
    entryPrice: 1.0965,
    exitDate: '2024-04-22T15:10:00',
    exitPrice: 1.0925,
    stopLoss: 1.0995,
    takeProfit: 1.0915,
    lotSize: 0.5,
    commission: 2.5,
    swap: 0,
    profit: 200,
    pips: 40,
    riskRewardRatio: 1.3,
    notes: 'Reversal at major resistance with bearish divergence',
    tags: ['Technical', 'Strong Trend'],
    strategy: 'Mean Reversion',
    status: 'CLOSED',
    session: 'LONDON',
    capitalGrowth: 200,
    riskPercentage: 1.5
  },
  {
    id: '5',
    pair: 'AUD/USD',
    type: 'BUY',
    entryDate: '2024-04-23T09:30:00',
    entryPrice: 0.6620,
    exitDate: null,
    exitPrice: null,
    stopLoss: 0.6580,
    takeProfit: 0.6690,
    lotSize: 0.3,
    commission: 1.8,
    swap: -0.8,
    profit: null,
    pips: null,
    riskRewardRatio: 1.75,
    notes: 'Support bounce with bullish candlestick pattern',
    tags: ['Technical', 'Good Setup'],
    strategy: 'Swing Trading',
    status: 'OPEN',
    session: 'SYDNEY',
    capitalGrowth: null,
    riskPercentage: 1.5
  },
  {
    id: '6',
    pair: 'USD/CAD',
    type: 'SELL',
    entryDate: '2024-04-20T13:15:00',
    entryPrice: 1.3640,
    exitDate: '2024-04-21T10:00:00',
    exitPrice: 1.3690,
    stopLoss: 1.3600,
    takeProfit: 1.3550,
    lotSize: 0.2,
    commission: 1.5,
    swap: -1.2,
    profit: -100,
    pips: -50,
    riskRewardRatio: 1.25,
    notes: 'News event caused unexpected spike',
    tags: ['News Event', 'Bad Entry'],
    strategy: 'News Trading',
    status: 'CLOSED',
    session: 'NEW_YORK',
    capitalGrowth: -100,
    riskPercentage: 1.5
  },
  {
    id: '7',
    pair: 'GBP/JPY',
    type: 'BUY',
    entryDate: '2024-04-22T11:00:00',
    entryPrice: 191.75,
    exitDate: '2024-04-23T14:30:00',
    exitPrice: 192.60,
    stopLoss: 191.25,
    takeProfit: 193.00,
    lotSize: 0.1,
    commission: 1.2,
    swap: 0,
    profit: 85,
    pips: 85,
    riskRewardRatio: 1.7,
    notes: 'Strong momentum after breaking resistance',
    tags: ['Technical', 'Good Setup', 'Strong Trend'],
    strategy: 'Breakout',
    status: 'CLOSED',
    session: 'LONDON',
    capitalGrowth: 85,
    riskPercentage: 1.5
  },
  {
    id: '8',
    pair: 'EUR/GBP',
    type: 'SELL',
    entryDate: '2024-04-23T09:45:00',
    entryPrice: 0.8580,
    exitDate: null,
    exitPrice: null,
    stopLoss: 0.8610,
    takeProfit: 0.8520,
    lotSize: 0.4,
    commission: 2.0,
    swap: -0.5,
    profit: null,
    pips: null,
    riskRewardRatio: 2.0,
    notes: 'Trading at key resistance level with bearish divergence',
    tags: ['Technical'],
    strategy: 'Mean Reversion',
    status: 'OPEN',
    session: 'SYDNEY',
    capitalGrowth: null,
    riskPercentage: 1.5
  }
].map(trade => ({
  ...trade,
  type: trade.type as 'BUY' | 'SELL' | 'NEUTRAL', // Type assertion for type
  status: trade.status as 'CLOSED' | 'OPEN', // Type assertion for status
  session: (trade.session || 'NEW_YORK') as TradingSession, // Cast to TradingSession
  capitalGrowth: trade.capitalGrowth ?? (trade.profit || 0),
  riskPercentage: trade.riskPercentage ?? Math.round(Math.random() * 3 + 1) // random between 1-4
}));

export const dummyMetrics: PerformanceMetric[] = [
  { name: 'Total Profit', value: '$430', change: 12.5, isPositive: true },
  { name: 'Win Rate', value: '62.5%', change: 5.2, isPositive: true },
  { name: 'Profit Factor', value: '1.85', change: 0.15, isPositive: true },
  { name: 'Average Profit', value: '$71.67', change: 8.3, isPositive: true },
  { name: 'Average Loss', value: '$90', change: -10.5, isPositive: false },
  { name: 'Max Drawdown', value: '$100', change: -15.2, isPositive: true },
  { name: 'Expected Return', value: '1.34', change: 0.08, isPositive: true },
  { name: 'Total Trades', value: '8', change: 3, isPositive: true }
];

export const dummyDailyPerformance: DailyPerformance[] = [
  { date: '2024-04-19', profit: 0, trades: 0 },
  { date: '2024-04-20', profit: 120, trades: 2 },
  { date: '2024-04-21', profit: 25, trades: 2 },
  { date: '2024-04-22', profit: 200, trades: 1 },
  { date: '2024-04-23', profit: 85, trades: 1 },
  { date: '2024-04-24', profit: 0, trades: 0 },
  { date: '2024-04-25', profit: 0, trades: 0 }
];

export const dummyPairPerformance: PairPerformance[] = [
  { pair: 'EUR/USD', totalProfit: 420, winRate: 100, tradesCount: 2 },
  { pair: 'GBP/USD', totalProfit: 105, winRate: 100, tradesCount: 1 },
  { pair: 'USD/JPY', totalProfit: -80, winRate: 0, tradesCount: 1 },
  { pair: 'AUD/USD', totalProfit: 0, winRate: 0, tradesCount: 1 },
  { pair: 'USD/CAD', totalProfit: -100, winRate: 0, tradesCount: 1 },
  { pair: 'GBP/JPY', totalProfit: 85, winRate: 100, tradesCount: 1 },
  { pair: 'EUR/GBP', totalProfit: 0, winRate: 0, tradesCount: 1 }
];

export const dummyTradeDistribution: TradeDistribution[] = [
  { name: 'Trend Following', value: 1 },
  { name: 'Breakout', value: 2 },
  { name: 'Mean Reversion', value: 2 },
  { name: 'News Trading', value: 1 },
  { name: 'Price Action', value: 1 },
  { name: 'Swing Trading', value: 1 }
];
